// Code generated by go generate; DO NOT EDIT.

package scoped

import (
	ds "github.com/ipfs/go-datastore"
)

type ds0 struct {
	ds.Datastore
}

func (d *ds0) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds1 struct {
	ds.Datastore
	ds.BatchingFeature
}

func (d *ds1) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds2 struct {
	ds.Datastore
	ds.CheckedFeature
}

func (d *ds2) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds3 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
}

func (d *ds3) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds4 struct {
	ds.Datastore
	ds.GCFeature
}

func (d *ds4) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds5 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
}

func (d *ds5) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds6 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
}

func (d *ds6) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds7 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
}

func (d *ds7) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds8 struct {
	ds.Datastore
	ds.PersistentFeature
}

func (d *ds8) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds9 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
}

func (d *ds9) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds10 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
}

func (d *ds10) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds11 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
}

func (d *ds11) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds12 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
}

func (d *ds12) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds13 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
}

func (d *ds13) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds14 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
}

func (d *ds14) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds15 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
}

func (d *ds15) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds16 struct {
	ds.Datastore
	ds.ScrubbedFeature
}

func (d *ds16) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds17 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.ScrubbedFeature
}

func (d *ds17) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds18 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.ScrubbedFeature
}

func (d *ds18) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds19 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.ScrubbedFeature
}

func (d *ds19) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds20 struct {
	ds.Datastore
	ds.GCFeature
	ds.ScrubbedFeature
}

func (d *ds20) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds21 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.ScrubbedFeature
}

func (d *ds21) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds22 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
}

func (d *ds22) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds23 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
}

func (d *ds23) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds24 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds24) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds25 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds25) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds26 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds26) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds27 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds27) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds28 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds28) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds29 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds29) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds30 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds30) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds31 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
}

func (d *ds31) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds32 struct {
	ds.Datastore
	ds.TTL
}

func (d *ds32) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds33 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.TTL
}

func (d *ds33) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds34 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.TTL
}

func (d *ds34) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds35 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.TTL
}

func (d *ds35) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds36 struct {
	ds.Datastore
	ds.GCFeature
	ds.TTL
}

func (d *ds36) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds37 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.TTL
}

func (d *ds37) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds38 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.TTL
}

func (d *ds38) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds39 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.TTL
}

func (d *ds39) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds40 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.TTL
}

func (d *ds40) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds41 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds41) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds42 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds42) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds43 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds43) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds44 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds44) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds45 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds45) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds46 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds46) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds47 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
}

func (d *ds47) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds48 struct {
	ds.Datastore
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds48) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds49 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds49) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds50 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds50) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds51 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds51) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds52 struct {
	ds.Datastore
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds52) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds53 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds53) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds54 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds54) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds55 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds55) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds56 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds56) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds57 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds57) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds58 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds58) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds59 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds59) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds60 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds60) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds61 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds61) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds62 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds62) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds63 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
}

func (d *ds63) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds64 struct {
	ds.Datastore
	ds.TxnFeature
}

func (d *ds64) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds65 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.TxnFeature
}

func (d *ds65) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds66 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.TxnFeature
}

func (d *ds66) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds67 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.TxnFeature
}

func (d *ds67) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds68 struct {
	ds.Datastore
	ds.GCFeature
	ds.TxnFeature
}

func (d *ds68) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds69 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.TxnFeature
}

func (d *ds69) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds70 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.TxnFeature
}

func (d *ds70) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds71 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.TxnFeature
}

func (d *ds71) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds72 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds72) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds73 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds73) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds74 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds74) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds75 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds75) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds76 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds76) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds77 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds77) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds78 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds78) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds79 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TxnFeature
}

func (d *ds79) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds80 struct {
	ds.Datastore
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds80) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds81 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds81) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds82 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds82) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds83 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds83) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds84 struct {
	ds.Datastore
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds84) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds85 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds85) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds86 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds86) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds87 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds87) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds88 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds88) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds89 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds89) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds90 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds90) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds91 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds91) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds92 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds92) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds93 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds93) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds94 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds94) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds95 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TxnFeature
}

func (d *ds95) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds96 struct {
	ds.Datastore
	ds.TTL
	ds.TxnFeature
}

func (d *ds96) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds97 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds97) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds98 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds98) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds99 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds99) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds100 struct {
	ds.Datastore
	ds.GCFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds100) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds101 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds101) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds102 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds102) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds103 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds103) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds104 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds104) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds105 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds105) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds106 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds106) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds107 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds107) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds108 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds108) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds109 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds109) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds110 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds110) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds111 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds111) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds112 struct {
	ds.Datastore
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds112) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds113 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds113) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds114 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds114) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds115 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds115) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds116 struct {
	ds.Datastore
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds116) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds117 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds117) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds118 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds118) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds119 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds119) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds120 struct {
	ds.Datastore
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds120) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds121 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds121) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds122 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds122) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds123 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds123) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds124 struct {
	ds.Datastore
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds124) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds125 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds125) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds126 struct {
	ds.Datastore
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds126) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

type ds127 struct {
	ds.Datastore
	ds.BatchingFeature
	ds.CheckedFeature
	ds.GCFeature
	ds.PersistentFeature
	ds.ScrubbedFeature
	ds.TTL
	ds.TxnFeature
}

func (d *ds127) Children() []ds.Datastore {
	return []ds.Datastore{d.Datastore}
}

var ctors = map[uint]func(ds.Datastore) ds.Datastore{
	0: func(dstore ds.Datastore) ds.Datastore {
		return &ds0{
			Datastore: dstore,
		}
	},
	1: func(dstore ds.Datastore) ds.Datastore {
		return &ds1{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
		}
	},
	2: func(dstore ds.Datastore) ds.Datastore {
		return &ds2{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
		}
	},
	3: func(dstore ds.Datastore) ds.Datastore {
		return &ds3{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
		}
	},
	4: func(dstore ds.Datastore) ds.Datastore {
		return &ds4{
			Datastore: dstore,
			GCFeature: dstore.(ds.GCDatastore),
		}
	},
	5: func(dstore ds.Datastore) ds.Datastore {
		return &ds5{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
		}
	},
	6: func(dstore ds.Datastore) ds.Datastore {
		return &ds6{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			GCFeature:      dstore.(ds.GCDatastore),
		}
	},
	7: func(dstore ds.Datastore) ds.Datastore {
		return &ds7{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
		}
	},
	8: func(dstore ds.Datastore) ds.Datastore {
		return &ds8{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	9: func(dstore ds.Datastore) ds.Datastore {
		return &ds9{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	10: func(dstore ds.Datastore) ds.Datastore {
		return &ds10{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	11: func(dstore ds.Datastore) ds.Datastore {
		return &ds11{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	12: func(dstore ds.Datastore) ds.Datastore {
		return &ds12{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	13: func(dstore ds.Datastore) ds.Datastore {
		return &ds13{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	14: func(dstore ds.Datastore) ds.Datastore {
		return &ds14{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	15: func(dstore ds.Datastore) ds.Datastore {
		return &ds15{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
		}
	},
	16: func(dstore ds.Datastore) ds.Datastore {
		return &ds16{
			Datastore:       dstore,
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	17: func(dstore ds.Datastore) ds.Datastore {
		return &ds17{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	18: func(dstore ds.Datastore) ds.Datastore {
		return &ds18{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	19: func(dstore ds.Datastore) ds.Datastore {
		return &ds19{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	20: func(dstore ds.Datastore) ds.Datastore {
		return &ds20{
			Datastore:       dstore,
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	21: func(dstore ds.Datastore) ds.Datastore {
		return &ds21{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	22: func(dstore ds.Datastore) ds.Datastore {
		return &ds22{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	23: func(dstore ds.Datastore) ds.Datastore {
		return &ds23{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
		}
	},
	24: func(dstore ds.Datastore) ds.Datastore {
		return &ds24{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	25: func(dstore ds.Datastore) ds.Datastore {
		return &ds25{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	26: func(dstore ds.Datastore) ds.Datastore {
		return &ds26{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	27: func(dstore ds.Datastore) ds.Datastore {
		return &ds27{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	28: func(dstore ds.Datastore) ds.Datastore {
		return &ds28{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	29: func(dstore ds.Datastore) ds.Datastore {
		return &ds29{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	30: func(dstore ds.Datastore) ds.Datastore {
		return &ds30{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	31: func(dstore ds.Datastore) ds.Datastore {
		return &ds31{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
		}
	},
	32: func(dstore ds.Datastore) ds.Datastore {
		return &ds32{
			Datastore: dstore,
			TTL:       dstore.(ds.TTLDatastore),
		}
	},
	33: func(dstore ds.Datastore) ds.Datastore {
		return &ds33{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	34: func(dstore ds.Datastore) ds.Datastore {
		return &ds34{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			TTL:            dstore.(ds.TTLDatastore),
		}
	},
	35: func(dstore ds.Datastore) ds.Datastore {
		return &ds35{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	36: func(dstore ds.Datastore) ds.Datastore {
		return &ds36{
			Datastore: dstore,
			GCFeature: dstore.(ds.GCDatastore),
			TTL:       dstore.(ds.TTLDatastore),
		}
	},
	37: func(dstore ds.Datastore) ds.Datastore {
		return &ds37{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	38: func(dstore ds.Datastore) ds.Datastore {
		return &ds38{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			GCFeature:      dstore.(ds.GCDatastore),
			TTL:            dstore.(ds.TTLDatastore),
		}
	},
	39: func(dstore ds.Datastore) ds.Datastore {
		return &ds39{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	40: func(dstore ds.Datastore) ds.Datastore {
		return &ds40{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	41: func(dstore ds.Datastore) ds.Datastore {
		return &ds41{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	42: func(dstore ds.Datastore) ds.Datastore {
		return &ds42{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	43: func(dstore ds.Datastore) ds.Datastore {
		return &ds43{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	44: func(dstore ds.Datastore) ds.Datastore {
		return &ds44{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	45: func(dstore ds.Datastore) ds.Datastore {
		return &ds45{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	46: func(dstore ds.Datastore) ds.Datastore {
		return &ds46{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	47: func(dstore ds.Datastore) ds.Datastore {
		return &ds47{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	48: func(dstore ds.Datastore) ds.Datastore {
		return &ds48{
			Datastore:       dstore,
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	49: func(dstore ds.Datastore) ds.Datastore {
		return &ds49{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	50: func(dstore ds.Datastore) ds.Datastore {
		return &ds50{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	51: func(dstore ds.Datastore) ds.Datastore {
		return &ds51{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	52: func(dstore ds.Datastore) ds.Datastore {
		return &ds52{
			Datastore:       dstore,
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	53: func(dstore ds.Datastore) ds.Datastore {
		return &ds53{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	54: func(dstore ds.Datastore) ds.Datastore {
		return &ds54{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	55: func(dstore ds.Datastore) ds.Datastore {
		return &ds55{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
		}
	},
	56: func(dstore ds.Datastore) ds.Datastore {
		return &ds56{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	57: func(dstore ds.Datastore) ds.Datastore {
		return &ds57{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	58: func(dstore ds.Datastore) ds.Datastore {
		return &ds58{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	59: func(dstore ds.Datastore) ds.Datastore {
		return &ds59{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	60: func(dstore ds.Datastore) ds.Datastore {
		return &ds60{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	61: func(dstore ds.Datastore) ds.Datastore {
		return &ds61{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	62: func(dstore ds.Datastore) ds.Datastore {
		return &ds62{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	63: func(dstore ds.Datastore) ds.Datastore {
		return &ds63{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
		}
	},
	64: func(dstore ds.Datastore) ds.Datastore {
		return &ds64{
			Datastore:  dstore,
			TxnFeature: dstore.(ds.TxnDatastore),
		}
	},
	65: func(dstore ds.Datastore) ds.Datastore {
		return &ds65{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	66: func(dstore ds.Datastore) ds.Datastore {
		return &ds66{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			TxnFeature:     dstore.(ds.TxnDatastore),
		}
	},
	67: func(dstore ds.Datastore) ds.Datastore {
		return &ds67{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	68: func(dstore ds.Datastore) ds.Datastore {
		return &ds68{
			Datastore:  dstore,
			GCFeature:  dstore.(ds.GCDatastore),
			TxnFeature: dstore.(ds.TxnDatastore),
		}
	},
	69: func(dstore ds.Datastore) ds.Datastore {
		return &ds69{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	70: func(dstore ds.Datastore) ds.Datastore {
		return &ds70{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			GCFeature:      dstore.(ds.GCDatastore),
			TxnFeature:     dstore.(ds.TxnDatastore),
		}
	},
	71: func(dstore ds.Datastore) ds.Datastore {
		return &ds71{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	72: func(dstore ds.Datastore) ds.Datastore {
		return &ds72{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	73: func(dstore ds.Datastore) ds.Datastore {
		return &ds73{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	74: func(dstore ds.Datastore) ds.Datastore {
		return &ds74{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	75: func(dstore ds.Datastore) ds.Datastore {
		return &ds75{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	76: func(dstore ds.Datastore) ds.Datastore {
		return &ds76{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	77: func(dstore ds.Datastore) ds.Datastore {
		return &ds77{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	78: func(dstore ds.Datastore) ds.Datastore {
		return &ds78{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	79: func(dstore ds.Datastore) ds.Datastore {
		return &ds79{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	80: func(dstore ds.Datastore) ds.Datastore {
		return &ds80{
			Datastore:       dstore,
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	81: func(dstore ds.Datastore) ds.Datastore {
		return &ds81{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	82: func(dstore ds.Datastore) ds.Datastore {
		return &ds82{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	83: func(dstore ds.Datastore) ds.Datastore {
		return &ds83{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	84: func(dstore ds.Datastore) ds.Datastore {
		return &ds84{
			Datastore:       dstore,
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	85: func(dstore ds.Datastore) ds.Datastore {
		return &ds85{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	86: func(dstore ds.Datastore) ds.Datastore {
		return &ds86{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	87: func(dstore ds.Datastore) ds.Datastore {
		return &ds87{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	88: func(dstore ds.Datastore) ds.Datastore {
		return &ds88{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	89: func(dstore ds.Datastore) ds.Datastore {
		return &ds89{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	90: func(dstore ds.Datastore) ds.Datastore {
		return &ds90{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	91: func(dstore ds.Datastore) ds.Datastore {
		return &ds91{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	92: func(dstore ds.Datastore) ds.Datastore {
		return &ds92{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	93: func(dstore ds.Datastore) ds.Datastore {
		return &ds93{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	94: func(dstore ds.Datastore) ds.Datastore {
		return &ds94{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	95: func(dstore ds.Datastore) ds.Datastore {
		return &ds95{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	96: func(dstore ds.Datastore) ds.Datastore {
		return &ds96{
			Datastore:  dstore,
			TTL:        dstore.(ds.TTLDatastore),
			TxnFeature: dstore.(ds.TxnDatastore),
		}
	},
	97: func(dstore ds.Datastore) ds.Datastore {
		return &ds97{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	98: func(dstore ds.Datastore) ds.Datastore {
		return &ds98{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			TTL:            dstore.(ds.TTLDatastore),
			TxnFeature:     dstore.(ds.TxnDatastore),
		}
	},
	99: func(dstore ds.Datastore) ds.Datastore {
		return &ds99{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	100: func(dstore ds.Datastore) ds.Datastore {
		return &ds100{
			Datastore:  dstore,
			GCFeature:  dstore.(ds.GCDatastore),
			TTL:        dstore.(ds.TTLDatastore),
			TxnFeature: dstore.(ds.TxnDatastore),
		}
	},
	101: func(dstore ds.Datastore) ds.Datastore {
		return &ds101{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	102: func(dstore ds.Datastore) ds.Datastore {
		return &ds102{
			Datastore:      dstore,
			CheckedFeature: dstore.(ds.CheckedDatastore),
			GCFeature:      dstore.(ds.GCDatastore),
			TTL:            dstore.(ds.TTLDatastore),
			TxnFeature:     dstore.(ds.TxnDatastore),
		}
	},
	103: func(dstore ds.Datastore) ds.Datastore {
		return &ds103{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	104: func(dstore ds.Datastore) ds.Datastore {
		return &ds104{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	105: func(dstore ds.Datastore) ds.Datastore {
		return &ds105{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	106: func(dstore ds.Datastore) ds.Datastore {
		return &ds106{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	107: func(dstore ds.Datastore) ds.Datastore {
		return &ds107{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	108: func(dstore ds.Datastore) ds.Datastore {
		return &ds108{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	109: func(dstore ds.Datastore) ds.Datastore {
		return &ds109{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	110: func(dstore ds.Datastore) ds.Datastore {
		return &ds110{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	111: func(dstore ds.Datastore) ds.Datastore {
		return &ds111{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	112: func(dstore ds.Datastore) ds.Datastore {
		return &ds112{
			Datastore:       dstore,
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	113: func(dstore ds.Datastore) ds.Datastore {
		return &ds113{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	114: func(dstore ds.Datastore) ds.Datastore {
		return &ds114{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	115: func(dstore ds.Datastore) ds.Datastore {
		return &ds115{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	116: func(dstore ds.Datastore) ds.Datastore {
		return &ds116{
			Datastore:       dstore,
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	117: func(dstore ds.Datastore) ds.Datastore {
		return &ds117{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	118: func(dstore ds.Datastore) ds.Datastore {
		return &ds118{
			Datastore:       dstore,
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	119: func(dstore ds.Datastore) ds.Datastore {
		return &ds119{
			Datastore:       dstore,
			BatchingFeature: dstore.(ds.Batching),
			CheckedFeature:  dstore.(ds.CheckedDatastore),
			GCFeature:       dstore.(ds.GCDatastore),
			ScrubbedFeature: dstore.(ds.ScrubbedDatastore),
			TTL:             dstore.(ds.TTLDatastore),
			TxnFeature:      dstore.(ds.TxnDatastore),
		}
	},
	120: func(dstore ds.Datastore) ds.Datastore {
		return &ds120{
			Datastore:         dstore,
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	121: func(dstore ds.Datastore) ds.Datastore {
		return &ds121{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	122: func(dstore ds.Datastore) ds.Datastore {
		return &ds122{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	123: func(dstore ds.Datastore) ds.Datastore {
		return &ds123{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	124: func(dstore ds.Datastore) ds.Datastore {
		return &ds124{
			Datastore:         dstore,
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	125: func(dstore ds.Datastore) ds.Datastore {
		return &ds125{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	126: func(dstore ds.Datastore) ds.Datastore {
		return &ds126{
			Datastore:         dstore,
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
	127: func(dstore ds.Datastore) ds.Datastore {
		return &ds127{
			Datastore:         dstore,
			BatchingFeature:   dstore.(ds.Batching),
			CheckedFeature:    dstore.(ds.CheckedDatastore),
			GCFeature:         dstore.(ds.GCDatastore),
			PersistentFeature: dstore.(ds.PersistentDatastore),
			ScrubbedFeature:   dstore.(ds.ScrubbedDatastore),
			TTL:               dstore.(ds.TTLDatastore),
			TxnFeature:        dstore.(ds.TxnDatastore),
		}
	},
}
